/**
 * Biome geometry paths extracted from Azgaar Fantasy Map Generator.
 * Generated by scripts/generate-tiles.mjs — do not edit by hand.
 * Paths are in SVG coordinate space (0 0 1438 755) — no transform needed for SVGOverlay.
 */

export interface BiomePath {
	d: string;
	fill: string;
}

export const BIOME_PATHS: BiomePath[] = [];
