/**
 * Terrain cluster data computed from relief placement density analysis.
 * Generated by scripts/generate-tiles.mjs — do not edit by hand.
 */

export interface TerrainCluster {
	type: string;
	cx: number;
	cy: number;
	count: number;
	scale: number;
}

export const TERRAIN_CLUSTERS: TerrainCluster[] = [
	{
		"type": "hill",
		"cx": 798.7,
		"cy": 95.8,
		"count": 18,
		"scale": 0.41
	},
	{
		"type": "hill",
		"cx": 879.3,
		"cy": 134.1,
		"count": 15,
		"scale": 0.4
	},
	{
		"type": "hill",
		"cx": 1198.9,
		"cy": 318.5,
		"count": 196,
		"scale": 1
	},
	{
		"type": "hill",
		"cx": 85.8,
		"cy": 306.8,
		"count": 43,
		"scale": 0.49
	},
	{
		"type": "mount",
		"cx": 842.9,
		"cy": 88.5,
		"count": 56,
		"scale": 1
	},
	{
		"type": "mount",
		"cx": 1191.5,
		"cy": 234.8,
		"count": 45,
		"scale": 0.4
	},
	{
		"type": "conifer",
		"cx": 971.1,
		"cy": 195.9,
		"count": 595,
		"scale": 1
	},
	{
		"type": "conifer",
		"cx": 1313.3,
		"cy": 213.6,
		"count": 65,
		"scale": 0.4
	},
	{
		"type": "deciduous",
		"cx": 823.4,
		"cy": 333.4,
		"count": 656,
		"scale": 1
	},
	{
		"type": "deciduous",
		"cx": 1270.6,
		"cy": 274.4,
		"count": 76,
		"scale": 0.44
	},
	{
		"type": "deciduous",
		"cx": 106.1,
		"cy": 402.3,
		"count": 141,
		"scale": 0.51
	},
	{
		"type": "deciduous",
		"cx": 515.4,
		"cy": 320.2,
		"count": 48,
		"scale": 0.42
	},
	{
		"type": "deciduous",
		"cx": 626.9,
		"cy": 331,
		"count": 45,
		"scale": 0.41
	},
	{
		"type": "deciduous",
		"cx": 1074.7,
		"cy": 329.6,
		"count": 79,
		"scale": 0.45
	},
	{
		"type": "deciduous",
		"cx": 202.1,
		"cy": 507.4,
		"count": 41,
		"scale": 0.41
	},
	{
		"type": "deciduous",
		"cx": 440.8,
		"cy": 562.8,
		"count": 30,
		"scale": 0.4
	},
	{
		"type": "acacia",
		"cx": 1225.3,
		"cy": 589.6,
		"count": 20,
		"scale": 0.4
	},
	{
		"type": "acacia",
		"cx": 1147.1,
		"cy": 630.7,
		"count": 47,
		"scale": 0.83
	},
	{
		"type": "acacia",
		"cx": 978.9,
		"cy": 684.9,
		"count": 58,
		"scale": 1
	},
	{
		"type": "palm",
		"cx": 1149.7,
		"cy": 634.1,
		"count": 23,
		"scale": 1
	},
	{
		"type": "palm",
		"cx": 987.4,
		"cy": 698.5,
		"count": 16,
		"scale": 0.4
	}
];
