/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    entries: Entry;
    cultures: Culture;
    paths: Path;
    disciplines: Discipline;
    techniques: Technique;
    patronages: Patronage;
    scores: Score;
    subscores: Subscore;
    'additional-scores': AdditionalScore;
    creatures: Creature;
    enhancements: Enhancement;
    timeline: Timeline;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    entries: EntriesSelect<false> | EntriesSelect<true>;
    cultures: CulturesSelect<false> | CulturesSelect<true>;
    paths: PathsSelect<false> | PathsSelect<true>;
    disciplines: DisciplinesSelect<false> | DisciplinesSelect<true>;
    techniques: TechniquesSelect<false> | TechniquesSelect<true>;
    patronages: PatronagesSelect<false> | PatronagesSelect<true>;
    scores: ScoresSelect<false> | ScoresSelect<true>;
    subscores: SubscoresSelect<false> | SubscoresSelect<true>;
    'additional-scores': AdditionalScoresSelect<false> | AdditionalScoresSelect<true>;
    creatures: CreaturesSelect<false> | CreaturesSelect<true>;
    enhancements: EnhancementsSelect<false> | EnhancementsSelect<true>;
    timeline: TimelineSelect<false> | TimelineSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * URL-safe identifier, e.g. "gameplay"
   */
  slug: string;
  description?: string | null;
  parent?: (number | null) | Category;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entries".
 */
export interface Entry {
  id: number;
  title: string;
  slug: string;
  author?: (number | null) | User;
  mainImage?: (number | null) | Media;
  category?: (number | null) | Category;
  publishedAt?: string | null;
  description?: string | null;
  cardDetails?:
    | {
        detailName?: string | null;
        detailDescription?: string | null;
        id?: string | null;
      }[]
    | null;
  toc?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  entryBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cultures".
 */
export interface Culture {
  id: number;
  title: string;
  entry?: (number | null) | Entry;
  mainImage?: (number | null) | Media;
  aspects?:
    | {
        aspectName?: string | null;
        /**
         * Stable ID used in saved characters. No spaces.
         */
        aspectId?: string | null;
        /**
         * Slug of the associated codex entry.
         */
        aspectContentSlug?: string | null;
        aspectDescription?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paths".
 */
export interface Path {
  id: number;
  title: string;
  latin?: string | null;
  slug?: string | null;
  mainImage?: (number | null) | Media;
  modifiers?:
    | {
        modifierSubscore: number | Subscore;
        /**
         * Positive or negative integer.
         */
        modifierValue?: number | null;
        id?: string | null;
      }[]
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: (number | null) | Category;
  toc?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  entryBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscores".
 */
export interface Subscore {
  id: number;
  title: string;
  /**
   * Stable identifier used in saved characters. Do not change after creation.
   */
  subscoreId?: string | null;
  score?: (number | null) | Score;
  defaultValue?: number | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scores".
 */
export interface Score {
  id: number;
  title: string;
  /**
   * Stable identifier used in saved characters. Do not change after creation.
   */
  scoreId?: string | null;
  subscores?: (number | Subscore)[] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disciplines".
 */
export interface Discipline {
  id: number;
  title: string;
  slug?: string | null;
  mainImage?: (number | null) | Media;
  paths?: (number | Path)[] | null;
  techniques?: (number | Technique)[] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: (number | null) | Category;
  toc?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  entryBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "techniques".
 */
export interface Technique {
  id: number;
  title: string;
  latin?: string | null;
  slug?: string | null;
  mainImage?: (number | null) | Media;
  /**
   * Rounds before this technique can be used again.
   */
  cooldown?: number | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: (number | null) | Category;
  toc?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  entryBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patronages".
 */
export interface Patronage {
  id: number;
  title: string;
  titleLatin?: string | null;
  epithet?: string | null;
  epithetLatin?: string | null;
  entry?: (number | null) | Entry;
  mainImage?: (number | null) | Media;
  effects?:
    | {
        title?: string | null;
        titleLatin?: string | null;
        entry?: (number | null) | Entry;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "additional-scores".
 */
export interface AdditionalScore {
  id: number;
  title: string;
  entry?: (number | null) | Entry;
  scores?:
    | (
        | {
            relationTo: 'scores';
            value: number | Score;
          }
        | {
            relationTo: 'subscores';
            value: number | Subscore;
          }
      )[]
    | null;
  calculation: 'sum' | 'difference' | 'multiply' | 'divide';
  additionalCalculations?:
    | {
        calculationType?: ('sum' | 'difference' | 'multiply' | 'divide') | null;
        value?: number | null;
        id?: string | null;
      }[]
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "creatures".
 */
export interface Creature {
  id: number;
  name: string;
  slug: string;
  /**
   * 1-2 sentences shown in the roller.
   */
  description?: string | null;
  mainImage?: (number | null) | Media;
  physical?: number | null;
  interpersonal?: number | null;
  intellect?: number | null;
  psyche?: number | null;
  health?: number | null;
  physicalShield?: number | null;
  psychicShield?: number | null;
  armorCapacity?: number | null;
  attacks?:
    | {
        /**
         * e.g., "Claw", "Bite"
         */
        name: string;
        /**
         * e.g., "2d6 + 3"
         */
        damage?: string | null;
        id?: string | null;
      }[]
    | null;
  specialAbilities?:
    | {
        name: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  challengeLevel?: ('harmless' | 'trivial' | 'easy' | 'moderate' | 'hard' | 'deadly') | null;
  /**
   * e.g., Beast, Construct, Humanoid
   */
  creatureType?: string | null;
  environments?:
    | {
        environment?: string | null;
        id?: string | null;
      }[]
    | null;
  isSwarm?: boolean | null;
  isUnique?: boolean | null;
  category?: (number | null) | Category;
  toc?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  entryBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enhancements".
 */
export interface Enhancement {
  id: number;
  title: string;
  latin?: string | null;
  entry?: (number | null) | Entry;
  /**
   * Rounds before this enhancement can be used again.
   */
  cooldown?: number | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline".
 */
export interface Timeline {
  id: number;
  title: string;
  /**
   * Positive or negative. Measured relative to the conflagratum magnum.
   */
  year: number;
  major?: boolean | null;
  icon?:
    | (
        | 'person'
        | 'people'
        | 'map'
        | 'waves'
        | 'mountain'
        | 'swords'
        | 'shield'
        | 'tree'
        | 'bird'
        | 'wolf'
        | 'snake'
        | 'fire'
        | 'poison'
        | 'hammer'
        | 'atom'
        | 'nuke'
      )
    | null;
  description?: string | null;
  /**
   * Full link to a Codex entry.
   */
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  entries?: {
    /**
     * Allow clients to find entries.
     */
    find?: boolean | null;
    /**
     * Allow clients to create entries.
     */
    create?: boolean | null;
    /**
     * Allow clients to update entries.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete entries.
     */
    delete?: boolean | null;
  };
  creatures?: {
    /**
     * Allow clients to find creatures.
     */
    find?: boolean | null;
    /**
     * Allow clients to create creatures.
     */
    create?: boolean | null;
    /**
     * Allow clients to update creatures.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete creatures.
     */
    delete?: boolean | null;
  };
  disciplines?: {
    /**
     * Allow clients to find disciplines.
     */
    find?: boolean | null;
    /**
     * Allow clients to create disciplines.
     */
    create?: boolean | null;
    /**
     * Allow clients to update disciplines.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete disciplines.
     */
    delete?: boolean | null;
  };
  techniques?: {
    /**
     * Allow clients to find techniques.
     */
    find?: boolean | null;
    /**
     * Allow clients to create techniques.
     */
    create?: boolean | null;
    /**
     * Allow clients to update techniques.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete techniques.
     */
    delete?: boolean | null;
  };
  paths?: {
    /**
     * Allow clients to find paths.
     */
    find?: boolean | null;
    /**
     * Allow clients to create paths.
     */
    create?: boolean | null;
    /**
     * Allow clients to update paths.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete paths.
     */
    delete?: boolean | null;
  };
  cultures?: {
    /**
     * Allow clients to find cultures.
     */
    find?: boolean | null;
    /**
     * Allow clients to create cultures.
     */
    create?: boolean | null;
    /**
     * Allow clients to update cultures.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete cultures.
     */
    delete?: boolean | null;
  };
  patronages?: {
    /**
     * Allow clients to find patronages.
     */
    find?: boolean | null;
    /**
     * Allow clients to create patronages.
     */
    create?: boolean | null;
    /**
     * Allow clients to update patronages.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete patronages.
     */
    delete?: boolean | null;
  };
  scores?: {
    /**
     * Allow clients to find scores.
     */
    find?: boolean | null;
    /**
     * Allow clients to create scores.
     */
    create?: boolean | null;
    /**
     * Allow clients to update scores.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete scores.
     */
    delete?: boolean | null;
  };
  subscores?: {
    /**
     * Allow clients to find subscores.
     */
    find?: boolean | null;
    /**
     * Allow clients to create subscores.
     */
    create?: boolean | null;
    /**
     * Allow clients to update subscores.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete subscores.
     */
    delete?: boolean | null;
  };
  additionalScores?: {
    /**
     * Allow clients to find additional-scores.
     */
    find?: boolean | null;
    /**
     * Allow clients to create additional-scores.
     */
    create?: boolean | null;
    /**
     * Allow clients to update additional-scores.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete additional-scores.
     */
    delete?: boolean | null;
  };
  enhancements?: {
    /**
     * Allow clients to find enhancements.
     */
    find?: boolean | null;
    /**
     * Allow clients to create enhancements.
     */
    create?: boolean | null;
    /**
     * Allow clients to update enhancements.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete enhancements.
     */
    delete?: boolean | null;
  };
  categories?: {
    /**
     * Allow clients to find categories.
     */
    find?: boolean | null;
    /**
     * Allow clients to create categories.
     */
    create?: boolean | null;
    /**
     * Allow clients to update categories.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete categories.
     */
    delete?: boolean | null;
  };
  timeline?: {
    /**
     * Allow clients to find timeline.
     */
    find?: boolean | null;
    /**
     * Allow clients to create timeline.
     */
    create?: boolean | null;
    /**
     * Allow clients to update timeline.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete timeline.
     */
    delete?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
    /**
     * Allow clients to create media.
     */
    create?: boolean | null;
    /**
     * Allow clients to update media.
     */
    update?: boolean | null;
    /**
     * Allow clients to delete media.
     */
    delete?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'entries';
        value: number | Entry;
      } | null)
    | ({
        relationTo: 'cultures';
        value: number | Culture;
      } | null)
    | ({
        relationTo: 'paths';
        value: number | Path;
      } | null)
    | ({
        relationTo: 'disciplines';
        value: number | Discipline;
      } | null)
    | ({
        relationTo: 'techniques';
        value: number | Technique;
      } | null)
    | ({
        relationTo: 'patronages';
        value: number | Patronage;
      } | null)
    | ({
        relationTo: 'scores';
        value: number | Score;
      } | null)
    | ({
        relationTo: 'subscores';
        value: number | Subscore;
      } | null)
    | ({
        relationTo: 'additional-scores';
        value: number | AdditionalScore;
      } | null)
    | ({
        relationTo: 'creatures';
        value: number | Creature;
      } | null)
    | ({
        relationTo: 'enhancements';
        value: number | Enhancement;
      } | null)
    | ({
        relationTo: 'timeline';
        value: number | Timeline;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  parent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entries_select".
 */
export interface EntriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  author?: T;
  mainImage?: T;
  category?: T;
  publishedAt?: T;
  description?: T;
  cardDetails?:
    | T
    | {
        detailName?: T;
        detailDescription?: T;
        id?: T;
      };
  toc?: T;
  entryBody?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cultures_select".
 */
export interface CulturesSelect<T extends boolean = true> {
  title?: T;
  entry?: T;
  mainImage?: T;
  aspects?:
    | T
    | {
        aspectName?: T;
        aspectId?: T;
        aspectContentSlug?: T;
        aspectDescription?: T;
        id?: T;
      };
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "paths_select".
 */
export interface PathsSelect<T extends boolean = true> {
  title?: T;
  latin?: T;
  slug?: T;
  mainImage?: T;
  modifiers?:
    | T
    | {
        modifierSubscore?: T;
        modifierValue?: T;
        id?: T;
      };
  description?: T;
  category?: T;
  toc?: T;
  entryBody?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disciplines_select".
 */
export interface DisciplinesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  mainImage?: T;
  paths?: T;
  techniques?: T;
  description?: T;
  category?: T;
  toc?: T;
  entryBody?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "techniques_select".
 */
export interface TechniquesSelect<T extends boolean = true> {
  title?: T;
  latin?: T;
  slug?: T;
  mainImage?: T;
  cooldown?: T;
  description?: T;
  category?: T;
  toc?: T;
  entryBody?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "patronages_select".
 */
export interface PatronagesSelect<T extends boolean = true> {
  title?: T;
  titleLatin?: T;
  epithet?: T;
  epithetLatin?: T;
  entry?: T;
  mainImage?: T;
  effects?:
    | T
    | {
        title?: T;
        titleLatin?: T;
        entry?: T;
        description?: T;
        id?: T;
      };
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scores_select".
 */
export interface ScoresSelect<T extends boolean = true> {
  title?: T;
  scoreId?: T;
  subscores?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscores_select".
 */
export interface SubscoresSelect<T extends boolean = true> {
  title?: T;
  subscoreId?: T;
  score?: T;
  defaultValue?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "additional-scores_select".
 */
export interface AdditionalScoresSelect<T extends boolean = true> {
  title?: T;
  entry?: T;
  scores?: T;
  calculation?: T;
  additionalCalculations?:
    | T
    | {
        calculationType?: T;
        value?: T;
        id?: T;
      };
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "creatures_select".
 */
export interface CreaturesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  mainImage?: T;
  physical?: T;
  interpersonal?: T;
  intellect?: T;
  psyche?: T;
  health?: T;
  physicalShield?: T;
  psychicShield?: T;
  armorCapacity?: T;
  attacks?:
    | T
    | {
        name?: T;
        damage?: T;
        id?: T;
      };
  specialAbilities?:
    | T
    | {
        name?: T;
        description?: T;
        id?: T;
      };
  challengeLevel?: T;
  creatureType?: T;
  environments?:
    | T
    | {
        environment?: T;
        id?: T;
      };
  isSwarm?: T;
  isUnique?: T;
  category?: T;
  toc?: T;
  entryBody?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enhancements_select".
 */
export interface EnhancementsSelect<T extends boolean = true> {
  title?: T;
  latin?: T;
  entry?: T;
  cooldown?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "timeline_select".
 */
export interface TimelineSelect<T extends boolean = true> {
  title?: T;
  year?: T;
  major?: T;
  icon?: T;
  description?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  entries?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  creatures?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  disciplines?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  techniques?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  paths?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  cultures?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  patronages?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  scores?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  subscores?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  additionalScores?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  enhancements?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  categories?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  timeline?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  media?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
        delete?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}