/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Creature = {
  _id: string;
  _type: "creature";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  category?: CategoryReference;
  toc?: Markdown;
  entryBody?: Markdown;
  physical?: number;
  interpersonal?: number;
  intellect?: number;
  psyche?: number;
  health?: number;
  physicalShield?: number;
  psychicShield?: number;
  armorCapacity?: number;
  attacks?: Array<{
    name?: string;
    damage?: string;
    _type: "attack";
    _key: string;
  }>;
  specialAbilities?: Array<{
    name?: string;
    description?: string;
    _type: "ability";
    _key: string;
  }>;
  challengeLevel?: "trivial" | "easy" | "moderate" | "hard" | "deadly";
  creatureType?: string;
  environments?: Array<string>;
  isSwarm?: boolean;
  isUnique?: boolean;
};

export type Markdown = string;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Timeline = {
  _id: string;
  _type: "timeline";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  URL?: string;
  icon?:
    | "person"
    | "people"
    | "map"
    | "waves"
    | "mountain"
    | "swords"
    | "shield"
    | "tree"
    | "bird"
    | "wolf"
    | "snake"
    | "fire"
    | "poison"
    | "hammer"
    | "atom"
    | "nuke";
  description?: string;
  major?: boolean;
  year?: number;
};

export type PathReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "path";
};

export type EntryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "entry";
};

export type SubscoreReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "subscore";
};

export type Gear = {
  _id: string;
  _type: "gear";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  latin?: string;
  type?: "weapon" | "armor" | "other";
  value?: number;
  paths?: Array<
    {
      _key: string;
    } & PathReference
  >;
  entry?: EntryReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  damageBonus?: number;
  shieldBonus?: number;
  modifiers?: Array<{
    modifierSubscore?: SubscoreReference;
    modifierValue?: number;
    _type: "modifier";
    _key: string;
  }>;
  description?: Markdown;
};

export type Enhancement = {
  _id: string;
  _type: "enhancement";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  latin?: string;
  entry?: EntryReference;
  cooldown?: number;
  description?: Markdown;
};

export type Technique = {
  _id: string;
  _type: "technique";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  latin?: string;
  slug?: Slug;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  cooldown?: number;
  description?: Markdown;
  category?: CategoryReference;
  toc?: Markdown;
  entryBody?: Markdown;
};

export type TechniqueReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "technique";
};

export type Discipline = {
  _id: string;
  _type: "discipline";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  paths?: Array<
    {
      _key: string;
    } & PathReference
  >;
  techniques?: Array<
    {
      _key: string;
    } & TechniqueReference
  >;
  description?: Markdown;
  category?: CategoryReference;
  toc?: Markdown;
  entryBody?: Markdown;
};

export type Patronage = {
  _id: string;
  _type: "patronage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  titleLatin?: string;
  epithet?: string;
  epithetLatin?: string;
  entry?: EntryReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  effects?: Array<{
    title?: string;
    titleLatin?: string;
    entry?: EntryReference;
    description?: Markdown;
    _type: "effect";
    _key: string;
  }>;
  description?: Markdown;
};

export type Path = {
  _id: string;
  _type: "path";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  latin?: string;
  slug?: Slug;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  modifiers?: Array<{
    modifierSubscore?: SubscoreReference;
    modifierValue?: number;
    _type: "modifier";
    _key: string;
  }>;
  description?: Markdown;
  category?: CategoryReference;
  toc?: Markdown;
  entryBody?: Markdown;
};

export type ScoreReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "score";
};

export type AdditionalScores = {
  _id: string;
  _type: "additionalScores";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  value?: number;
  entry?: EntryReference;
  scores?: ArrayOf<ScoreReference | SubscoreReference>;
  calculation?: "sum" | "difference" | "multiply" | "divide";
  additionalCalculations?: Array<{
    calculationType?: "sum" | "difference" | "multiply" | "divide";
    value?: number;
    _type: "additionalCalculation";
    _key: string;
  }>;
  description?: Markdown;
};

export type Subscore = {
  _id: string;
  _type: "subscore";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  score?: ScoreReference;
  defaultValue?: number;
  description?: Markdown;
};

export type Score = {
  _id: string;
  _type: "score";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  id?: string;
  subscores?: Array<
    {
      _key: string;
    } & SubscoreReference
  >;
  description?: Markdown;
};

export type Culture = {
  _id: string;
  _type: "culture";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  entry?: EntryReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  aspects?: Array<{
    aspectName?: string;
    aspectId?: string;
    aspectContentSlug?: string;
    aspectDescription?: Markdown;
    _type: "aspect";
    _key: string;
  }>;
  description?: Markdown;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Entry = {
  _id: string;
  _type: "entry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: AuthorReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  category?: CategoryReference;
  publishedAt?: string;
  cardDetails?: Array<{
    detailName?: string;
    detailDescription?: string;
    _type: "cardDetail";
    _key: string;
  }>;
  description?: string;
  toc?: Markdown;
  entryBody?: Markdown;
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: AuthorReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
  body?: BlockContent;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  chipColor?: Color;
  description?: string;
  parent?: CategoryReference;
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | CategoryReference
  | Creature
  | Markdown
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Timeline
  | PathReference
  | EntryReference
  | SubscoreReference
  | Gear
  | Enhancement
  | Technique
  | TechniqueReference
  | Discipline
  | Patronage
  | Path
  | ScoreReference
  | AdditionalScores
  | Subscore
  | Score
  | Culture
  | AuthorReference
  | Entry
  | Post
  | BlockContent
  | Author
  | Category
  | Color
  | RgbaColor
  | HsvaColor
  | HslaColor
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: src/sanity/lib/queries.ts
// Variable: CULTURES_QUERY
// Query: *[_type == "culture"]{  _id, title, entry->{ slug }, aspects, mainImage, description}
export type CULTURES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  entry: {
    slug: Slug | null;
  } | null;
  aspects: Array<{
    aspectName?: string;
    aspectId?: string;
    aspectContentSlug?: string;
    aspectDescription?: Markdown;
    _type: "aspect";
    _key: string;
  }> | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  description: Markdown | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: SCORES_QUERY
// Query: *[_type == "score"]| order(title asc){  _id, title, id, subscores[]->{_id, title, id, defaultValue, description}, description}
export type SCORES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  id: string | null;
  subscores: Array<{
    _id: string;
    title: string | null;
    id: null;
    defaultValue: number | null;
    description: Markdown | null;
  }> | null;
  description: Markdown | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: SUBSCORES_QUERY
// Query: *[_type == "subscore"]{  _id, title, score->{_id, title, id}, defaultValue, description}
export type SUBSCORES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  score: {
    _id: string;
    title: string | null;
    id: string | null;
  } | null;
  defaultValue: number | null;
  description: Markdown | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: ADDITIONAL_SCORES_QUERY
// Query: *[_type == "additionalScores"]{  _id, title, value, entry->{ slug }, scores[]->{ _id, title }, calculation, additionalCalculations[], description}
export type ADDITIONAL_SCORES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  value: number | null;
  entry: {
    slug: Slug | null;
  } | null;
  scores: Array<{
    _id: string;
    title: string | null;
  }> | null;
  calculation: "difference" | "divide" | "multiply" | "sum" | null;
  additionalCalculations: Array<{
    calculationType?: "difference" | "divide" | "multiply" | "sum";
    value?: number;
    _type: "additionalCalculation";
    _key: string;
  }> | null;
  description: Markdown | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PATHS_QUERY
// Query: *[_type == "path"]{  _id, title, latin, slug, mainImage, modifiers[]{ modifierSubscore->{ _id, title, score->{ _id, title } }, modifierValue}, description}
export type PATHS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  latin: string | null;
  slug: Slug | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  modifiers: Array<{
    modifierSubscore: {
      _id: string;
      title: string | null;
      score: {
        _id: string;
        title: string | null;
      } | null;
    } | null;
    modifierValue: number | null;
  }> | null;
  description: Markdown | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: PATRONAGES_QUERY
// Query: *[_type == "patronage"]{  _id, title, titleLatin, epithet, epithetLatin, entry->{ slug }, mainImage, effects[]{ title, titleLatin, entry->{ slug }, description }, description}
export type PATRONAGES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  titleLatin: string | null;
  epithet: string | null;
  epithetLatin: string | null;
  entry: {
    slug: Slug | null;
  } | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  effects: Array<{
    title: string | null;
    titleLatin: string | null;
    entry: {
      slug: Slug | null;
    } | null;
    description: Markdown | null;
  }> | null;
  description: Markdown | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: DISCIPLINES_QUERY
// Query: *[_type == "discipline"]| order(title asc){  _id, title, slug, paths[]->{_id, title }, techniques[]->{_id, title, latin, cooldown, description }, description}
export type DISCIPLINES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  paths: Array<{
    _id: string;
    title: string | null;
  }> | null;
  techniques: Array<{
    _id: string;
    title: string | null;
    latin: string | null;
    cooldown: number | null;
    description: Markdown | null;
  }> | null;
  description: Markdown | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: GEAR_QUERY
// Query: *[_type == "gear"]{  _id, title, latin, type, value, damageBonus, shieldBonus, entry, mainImage, paths[]->{ _id }, modifiers[]{ modifierSubscore->{ _id, title, score->{ _id, title } }, modifierValue}, description}
export type GEAR_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  latin: string | null;
  type: "armor" | "other" | "weapon" | null;
  value: number | null;
  damageBonus: number | null;
  shieldBonus: number | null;
  entry: EntryReference | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  paths: Array<{
    _id: string;
  }> | null;
  modifiers: Array<{
    modifierSubscore: {
      _id: string;
      title: string | null;
      score: {
        _id: string;
        title: string | null;
      } | null;
    } | null;
    modifierValue: number | null;
  }> | null;
  description: Markdown | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: GEAR_PAGE_QUERY
// Query: *[_type == "gear" && type == $slug]| order( title asc, path.title asc ){  _id, title, latin, type, value, damageBonus, shieldBonus, entry, mainImage, paths[]->{ _id, title }, modifiers[]{ modifierSubscore->{ _id, title, score->{ _id, title } }, modifierValue}, description}
export type GEAR_PAGE_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  latin: string | null;
  type: "armor" | "other" | "weapon" | null;
  value: number | null;
  damageBonus: number | null;
  shieldBonus: number | null;
  entry: EntryReference | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  paths: Array<{
    _id: string;
    title: string | null;
  }> | null;
  modifiers: Array<{
    modifierSubscore: {
      _id: string;
      title: string | null;
      score: {
        _id: string;
        title: string | null;
      } | null;
    } | null;
    modifierValue: number | null;
  }> | null;
  description: Markdown | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: CHARACTER_MANAGER_QUERY
// Query: {  "cultures": *[_type == "culture"]{  _id, title, entry->{ slug }, aspects, mainImage, description},  "paths": *[_type == "path"]{  _id, title, latin, slug, mainImage, modifiers[]{ modifierSubscore->{ _id, title, score->{ _id, title } }, modifierValue}, description},  "patronages": *[_type == "patronage"]{  _id, title, titleLatin, epithet, epithetLatin, entry->{ slug }, mainImage, effects[]{ title, titleLatin, entry->{ slug }, description }, description},  "disciplines": *[_type == "discipline"]| order(title asc){  _id, title, slug, paths[]->{_id, title }, techniques[]->{_id, title, latin, cooldown, description }, description},  "scores": *[_type == "score"]| order(title asc){  _id, title, id, subscores[]->{_id, title, id, defaultValue, description}, description},  "subscores": *[_type == "subscore"]{  _id, title, score->{_id, title, id}, defaultValue, description},  "additionalScores": *[_type == "additionalScores"]{  _id, title, value, entry->{ slug }, scores[]->{ _id, title }, calculation, additionalCalculations[], description},  "gear": *[_type == "gear"]{  _id, title, latin, type, value, damageBonus, shieldBonus, entry, mainImage, paths[]->{ _id }, modifiers[]{ modifierSubscore->{ _id, title, score->{ _id, title } }, modifierValue}, description},}
export type CHARACTER_MANAGER_QUERY_RESULT = {
  cultures: Array<{
    _id: string;
    title: string | null;
    entry: {
      slug: Slug | null;
    } | null;
    aspects: Array<{
      aspectName?: string;
      aspectId?: string;
      aspectContentSlug?: string;
      aspectDescription?: Markdown;
      _type: "aspect";
      _key: string;
    }> | null;
    mainImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    description: Markdown | null;
  }>;
  paths: Array<{
    _id: string;
    title: string | null;
    latin: string | null;
    slug: Slug | null;
    mainImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    modifiers: Array<{
      modifierSubscore: {
        _id: string;
        title: string | null;
        score: {
          _id: string;
          title: string | null;
        } | null;
      } | null;
      modifierValue: number | null;
    }> | null;
    description: Markdown | null;
  }>;
  patronages: Array<{
    _id: string;
    title: string | null;
    titleLatin: string | null;
    epithet: string | null;
    epithetLatin: string | null;
    entry: {
      slug: Slug | null;
    } | null;
    mainImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    effects: Array<{
      title: string | null;
      titleLatin: string | null;
      entry: {
        slug: Slug | null;
      } | null;
      description: Markdown | null;
    }> | null;
    description: Markdown | null;
  }>;
  disciplines: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    paths: Array<{
      _id: string;
      title: string | null;
    }> | null;
    techniques: Array<{
      _id: string;
      title: string | null;
      latin: string | null;
      cooldown: number | null;
      description: Markdown | null;
    }> | null;
    description: Markdown | null;
  }>;
  scores: Array<{
    _id: string;
    title: string | null;
    id: string | null;
    subscores: Array<{
      _id: string;
      title: string | null;
      id: null;
      defaultValue: number | null;
      description: Markdown | null;
    }> | null;
    description: Markdown | null;
  }>;
  subscores: Array<{
    _id: string;
    title: string | null;
    score: {
      _id: string;
      title: string | null;
      id: string | null;
    } | null;
    defaultValue: number | null;
    description: Markdown | null;
  }>;
  additionalScores: Array<{
    _id: string;
    title: string | null;
    value: number | null;
    entry: {
      slug: Slug | null;
    } | null;
    scores: Array<{
      _id: string;
      title: string | null;
    }> | null;
    calculation: "difference" | "divide" | "multiply" | "sum" | null;
    additionalCalculations: Array<{
      calculationType?: "difference" | "divide" | "multiply" | "sum";
      value?: number;
      _type: "additionalCalculation";
      _key: string;
    }> | null;
    description: Markdown | null;
  }>;
  gear: Array<{
    _id: string;
    title: string | null;
    latin: string | null;
    type: "armor" | "other" | "weapon" | null;
    value: number | null;
    damageBonus: number | null;
    shieldBonus: number | null;
    entry: EntryReference | null;
    mainImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    paths: Array<{
      _id: string;
    }> | null;
    modifiers: Array<{
      modifierSubscore: {
        _id: string;
        title: string | null;
        score: {
          _id: string;
          title: string | null;
        } | null;
      } | null;
      modifierValue: number | null;
    }> | null;
    description: Markdown | null;
  }>;
};

// Source: src/sanity/lib/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)][0...12]{  _id, title, slug}
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{  title, body, mainImage, categories[]->{title, slug}}
export type POST_QUERY_RESULT = {
  title: string | null;
  body: BlockContent | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  categories: Array<{
    title: string | null;
    slug: Slug | null;
  }> | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: ENTRIES_QUERY
// Query: *[_type in ["entry", "creature", "discipline", "technique", "path"] && defined(slug.current)]| order(coalesce(title, name) asc)[0...96]{  _id,  _type,  "title": coalesce(title, name),  slug,  description}
export type ENTRIES_QUERY_RESULT = Array<
  | {
      _id: string;
      _type: "creature";
      title: string | null;
      slug: Slug | null;
      description: string | null;
    }
  | {
      _id: string;
      _type: "discipline";
      title: string | null;
      slug: Slug | null;
      description: Markdown | null;
    }
  | {
      _id: string;
      _type: "entry";
      title: string | null;
      slug: Slug | null;
      description: string | null;
    }
  | {
      _id: string;
      _type: "path";
      title: string | null;
      slug: Slug | null;
      description: Markdown | null;
    }
  | {
      _id: string;
      _type: "technique";
      title: string | null;
      slug: Slug | null;
      description: Markdown | null;
    }
>;

// Source: src/sanity/lib/queries.ts
// Variable: ENTRIES_COUNT_QUERY
// Query: count(*[_type in ["entry", "creature", "discipline", "technique", "path"] && defined(slug.current)])
export type ENTRIES_COUNT_QUERY_RESULT = number;

// Source: src/sanity/lib/queries.ts
// Variable: ENTRY_QUERY
// Query: *[_type == "entry" && slug.current == $slug][0]{  _type,  title,  cardDetails,  entryBody,  toc,  mainImage,  publishedAt,  author->{name, slug},  category->{title, slug, parent->{title, slug, parent->{title, slug, parent->{title, slug, parent->{}}}}}}
export type ENTRY_QUERY_RESULT = {
  _type: "entry";
  title: string | null;
  cardDetails: Array<{
    detailName?: string;
    detailDescription?: string;
    _type: "cardDetail";
    _key: string;
  }> | null;
  entryBody: Markdown | null;
  toc: Markdown | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  publishedAt: string | null;
  author: {
    name: string | null;
    slug: Slug | null;
  } | null;
  category: {
    title: string | null;
    slug: Slug | null;
    parent: {
      title: string | null;
      slug: Slug | null;
      parent: {
        title: string | null;
        slug: Slug | null;
        parent: {
          title: string | null;
          slug: Slug | null;
          parent: {} | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: UNIFIED_ENTRY_QUERY
// Query: *[_type in ["entry", "creature", "discipline", "technique", "path"] && slug.current == $slug][0]{  _type,  "title": coalesce(title, name),  slug,  description,  entryBody,  toc,  mainImage,  category->{title, slug, parent->{title, slug, parent->{title, slug, parent->{title, slug, parent->{}}}}},  // Entry-specific fields  _type == "entry" => {    cardDetails,    publishedAt,    author->{name, slug}  },  // Creature-specific fields  _type == "creature" => {    "name": name,    physical,    interpersonal,    intellect,    psyche,    health,    physicalShield,    psychicShield,    armorCapacity,    attacks,    specialAbilities,    challengeLevel,    creatureType,    environments,    isSwarm,    isUnique  },  // Discipline-specific fields  _type == "discipline" => {    paths[]->{_id, title, slug},    techniques[]->{_id, title, latin, slug, cooldown, description}  },  // Technique-specific fields  _type == "technique" => {    latin,    cooldown  },  // Path-specific fields  _type == "path" => {    latin,    modifiers[]{ modifierSubscore->{ _id, title, score->{ _id, title } }, modifierValue }  }}
export type UNIFIED_ENTRY_QUERY_RESULT =
  | {
      _type: "creature";
      title: string | null;
      slug: Slug | null;
      description: string | null;
      entryBody: Markdown | null;
      toc: Markdown | null;
      mainImage: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      } | null;
      category: {
        title: string | null;
        slug: Slug | null;
        parent: {
          title: string | null;
          slug: Slug | null;
          parent: {
            title: string | null;
            slug: Slug | null;
            parent: {
              title: string | null;
              slug: Slug | null;
              parent: {} | null;
            } | null;
          } | null;
        } | null;
      } | null;
      name: string | null;
      physical: number | null;
      interpersonal: number | null;
      intellect: number | null;
      psyche: number | null;
      health: number | null;
      physicalShield: number | null;
      psychicShield: number | null;
      armorCapacity: number | null;
      attacks: Array<{
        name?: string;
        damage?: string;
        _type: "attack";
        _key: string;
      }> | null;
      specialAbilities: Array<{
        name?: string;
        description?: string;
        _type: "ability";
        _key: string;
      }> | null;
      challengeLevel:
        | "deadly"
        | "easy"
        | "hard"
        | "moderate"
        | "trivial"
        | null;
      creatureType: string | null;
      environments: Array<string> | null;
      isSwarm: boolean | null;
      isUnique: boolean | null;
    }
  | {
      _type: "discipline";
      title: string | null;
      slug: Slug | null;
      description: Markdown | null;
      entryBody: Markdown | null;
      toc: Markdown | null;
      mainImage: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      } | null;
      category: {
        title: string | null;
        slug: Slug | null;
        parent: {
          title: string | null;
          slug: Slug | null;
          parent: {
            title: string | null;
            slug: Slug | null;
            parent: {
              title: string | null;
              slug: Slug | null;
              parent: {} | null;
            } | null;
          } | null;
        } | null;
      } | null;
      paths: Array<{
        _id: string;
        title: string | null;
        slug: Slug | null;
      }> | null;
      techniques: Array<{
        _id: string;
        title: string | null;
        latin: string | null;
        slug: Slug | null;
        cooldown: number | null;
        description: Markdown | null;
      }> | null;
    }
  | {
      _type: "entry";
      title: string | null;
      slug: Slug | null;
      description: string | null;
      entryBody: Markdown | null;
      toc: Markdown | null;
      mainImage: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      } | null;
      category: {
        title: string | null;
        slug: Slug | null;
        parent: {
          title: string | null;
          slug: Slug | null;
          parent: {
            title: string | null;
            slug: Slug | null;
            parent: {
              title: string | null;
              slug: Slug | null;
              parent: {} | null;
            } | null;
          } | null;
        } | null;
      } | null;
      cardDetails: Array<{
        detailName?: string;
        detailDescription?: string;
        _type: "cardDetail";
        _key: string;
      }> | null;
      publishedAt: string | null;
      author: {
        name: string | null;
        slug: Slug | null;
      } | null;
    }
  | {
      _type: "path";
      title: string | null;
      slug: Slug | null;
      description: Markdown | null;
      entryBody: Markdown | null;
      toc: Markdown | null;
      mainImage: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      } | null;
      category: {
        title: string | null;
        slug: Slug | null;
        parent: {
          title: string | null;
          slug: Slug | null;
          parent: {
            title: string | null;
            slug: Slug | null;
            parent: {
              title: string | null;
              slug: Slug | null;
              parent: {} | null;
            } | null;
          } | null;
        } | null;
      } | null;
      latin: string | null;
      modifiers: Array<{
        modifierSubscore: {
          _id: string;
          title: string | null;
          score: {
            _id: string;
            title: string | null;
          } | null;
        } | null;
        modifierValue: number | null;
      }> | null;
    }
  | {
      _type: "technique";
      title: string | null;
      slug: Slug | null;
      description: Markdown | null;
      entryBody: Markdown | null;
      toc: Markdown | null;
      mainImage: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: "image";
      } | null;
      category: {
        title: string | null;
        slug: Slug | null;
        parent: {
          title: string | null;
          slug: Slug | null;
          parent: {
            title: string | null;
            slug: Slug | null;
            parent: {
              title: string | null;
              slug: Slug | null;
              parent: {} | null;
            } | null;
          } | null;
        } | null;
      } | null;
      latin: string | null;
      cooldown: number | null;
    }
  | null;

// Source: src/sanity/lib/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category" && defined(slug.current)][0...12]{  _id, title, slug, description}
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: CATEGORY_QUERY
// Query: *[_type == "category" && slug.current == $slug][0]{  _id,  title,  slug,  description,  parent->{title, slug},  "entries": *[_type in ["entry", "creature", "discipline", "technique", "path"] && references(^._id)]| order(coalesce(title, name) asc) [0...96]{    _id,    _type,    "title": coalesce(title, name),    slug,    description  },  "children": *[_type == "category" && references(^._id)]{    _id,    title,    slug,    description  }}
export type CATEGORY_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: Slug | null;
  description: string | null;
  parent: {
    title: string | null;
    slug: Slug | null;
  } | null;
  entries: Array<
    | {
        _id: string;
        _type: "creature";
        title: string | null;
        slug: Slug | null;
        description: string | null;
      }
    | {
        _id: string;
        _type: "discipline";
        title: string | null;
        slug: Slug | null;
        description: Markdown | null;
      }
    | {
        _id: string;
        _type: "entry";
        title: string | null;
        slug: Slug | null;
        description: string | null;
      }
    | {
        _id: string;
        _type: "path";
        title: string | null;
        slug: Slug | null;
        description: Markdown | null;
      }
    | {
        _id: string;
        _type: "technique";
        title: string | null;
        slug: Slug | null;
        description: Markdown | null;
      }
  >;
  children: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    description: string | null;
  }>;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: TIMELINE_QUERY
// Query: *[_type == "timeline"]| order(year desc) {  _id, title, URL, year, major, icon, description}
export type TIMELINE_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  URL: string | null;
  year: number | null;
  major: boolean | null;
  icon:
    | "atom"
    | "bird"
    | "fire"
    | "hammer"
    | "map"
    | "mountain"
    | "nuke"
    | "people"
    | "person"
    | "poison"
    | "shield"
    | "snake"
    | "swords"
    | "tree"
    | "waves"
    | "wolf"
    | null;
  description: string | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: CREATURES_QUERY
// Query: *[_type == "creature"]| order(name asc) {  _id,  name,  slug,  description,  mainImage,  physical,  interpersonal,  intellect,  psyche,  health,  physicalShield,  psychicShield,  armorCapacity,  attacks,  specialAbilities,  challengeLevel,  creatureType,  environments,  isSwarm,  isUnique}
export type CREATURES_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: Slug | null;
  description: string | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  physical: number | null;
  interpersonal: number | null;
  intellect: number | null;
  psyche: number | null;
  health: number | null;
  physicalShield: number | null;
  psychicShield: number | null;
  armorCapacity: number | null;
  attacks: Array<{
    name?: string;
    damage?: string;
    _type: "attack";
    _key: string;
  }> | null;
  specialAbilities: Array<{
    name?: string;
    description?: string;
    _type: "ability";
    _key: string;
  }> | null;
  challengeLevel: "deadly" | "easy" | "hard" | "moderate" | "trivial" | null;
  creatureType: string | null;
  environments: Array<string> | null;
  isSwarm: boolean | null;
  isUnique: boolean | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: CREATURE_QUERY
// Query: *[_type == "creature" && slug.current == $slug][0]{  _id,  name,  slug,  description,  mainImage,  physical,  interpersonal,  intellect,  psyche,  health,  physicalShield,  psychicShield,  armorCapacity,  attacks,  specialAbilities,  challengeLevel,  creatureType,  environments,  isSwarm,  isUnique,  entryBody,  toc,  category->{title, slug, parent->{title, slug, parent->{title, slug, parent->{title, slug, parent->{}}}}}}
export type CREATURE_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: Slug | null;
  description: string | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  physical: number | null;
  interpersonal: number | null;
  intellect: number | null;
  psyche: number | null;
  health: number | null;
  physicalShield: number | null;
  psychicShield: number | null;
  armorCapacity: number | null;
  attacks: Array<{
    name?: string;
    damage?: string;
    _type: "attack";
    _key: string;
  }> | null;
  specialAbilities: Array<{
    name?: string;
    description?: string;
    _type: "ability";
    _key: string;
  }> | null;
  challengeLevel: "deadly" | "easy" | "hard" | "moderate" | "trivial" | null;
  creatureType: string | null;
  environments: Array<string> | null;
  isSwarm: boolean | null;
  isUnique: boolean | null;
  entryBody: Markdown | null;
  toc: Markdown | null;
  category: {
    title: string | null;
    slug: Slug | null;
    parent: {
      title: string | null;
      slug: Slug | null;
      parent: {
        title: string | null;
        slug: Slug | null;
        parent: {
          title: string | null;
          slug: Slug | null;
          parent: {} | null;
        } | null;
      } | null;
    } | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: CREATURE_FILTERS_QUERY
// Query: {  "environments": array::unique(*[_type == "creature"].environments[]),  "creatureTypes": array::unique(*[_type == "creature"].creatureType),  "challengeLevels": ["trivial", "easy", "moderate", "hard", "deadly"]}
export type CREATURE_FILTERS_QUERY_RESULT = {
  environments: Array<string | null>;
  creatureTypes: Array<string | null>;
  challengeLevels: Array<"deadly" | "easy" | "hard" | "moderate" | "trivial">;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "culture"]{\n  _id, title, entry->{ slug }, aspects, mainImage, description\n}': CULTURES_QUERY_RESULT;
    '*[_type == "score"]| order(title asc){\n  _id, title, id, subscores[]->{_id, title, id, defaultValue, description}, description\n}': SCORES_QUERY_RESULT;
    '*[_type == "subscore"]{\n  _id, title, score->{_id, title, id}, defaultValue, description\n}': SUBSCORES_QUERY_RESULT;
    '*[_type == "additionalScores"]{\n  _id, title, value, entry->{ slug }, scores[]->{ _id, title }, calculation, additionalCalculations[], description\n}': ADDITIONAL_SCORES_QUERY_RESULT;
    '*[_type == "path"]{\n  _id, title, latin, slug, mainImage, modifiers[]{ modifierSubscore->{ _id, title, score->{ _id, title } }, modifierValue}, description\n}': PATHS_QUERY_RESULT;
    '*[_type == "patronage"]{\n  _id, title, titleLatin, epithet, epithetLatin, entry->{ slug }, mainImage, effects[]{ title, titleLatin, entry->{ slug }, description }, description\n}': PATRONAGES_QUERY_RESULT;
    '*[_type == "discipline"]| order(title asc){\n  _id, title, slug, paths[]->{_id, title }, techniques[]->{_id, title, latin, cooldown, description }, description\n}': DISCIPLINES_QUERY_RESULT;
    '*[_type == "gear"]{\n  _id, title, latin, type, value, damageBonus, shieldBonus, entry, mainImage, paths[]->{ _id }, modifiers[]{ modifierSubscore->{ _id, title, score->{ _id, title } }, modifierValue}, description\n}': GEAR_QUERY_RESULT;
    '*[_type == "gear" && type == $slug]| order( title asc, path.title asc ){\n  _id, title, latin, type, value, damageBonus, shieldBonus, entry, mainImage, paths[]->{ _id, title }, modifiers[]{ modifierSubscore->{ _id, title, score->{ _id, title } }, modifierValue}, description\n}': GEAR_PAGE_QUERY_RESULT;
    '{\n  "cultures": *[_type == "culture"]{\n  _id, title, entry->{ slug }, aspects, mainImage, description\n},\n  "paths": *[_type == "path"]{\n  _id, title, latin, slug, mainImage, modifiers[]{ modifierSubscore->{ _id, title, score->{ _id, title } }, modifierValue}, description\n},\n  "patronages": *[_type == "patronage"]{\n  _id, title, titleLatin, epithet, epithetLatin, entry->{ slug }, mainImage, effects[]{ title, titleLatin, entry->{ slug }, description }, description\n},\n  "disciplines": *[_type == "discipline"]| order(title asc){\n  _id, title, slug, paths[]->{_id, title }, techniques[]->{_id, title, latin, cooldown, description }, description\n},\n  "scores": *[_type == "score"]| order(title asc){\n  _id, title, id, subscores[]->{_id, title, id, defaultValue, description}, description\n},\n  "subscores": *[_type == "subscore"]{\n  _id, title, score->{_id, title, id}, defaultValue, description\n},\n  "additionalScores": *[_type == "additionalScores"]{\n  _id, title, value, entry->{ slug }, scores[]->{ _id, title }, calculation, additionalCalculations[], description\n},\n  "gear": *[_type == "gear"]{\n  _id, title, latin, type, value, damageBonus, shieldBonus, entry, mainImage, paths[]->{ _id }, modifiers[]{ modifierSubscore->{ _id, title, score->{ _id, title } }, modifierValue}, description\n},\n}': CHARACTER_MANAGER_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current)][0...12]{\n  _id, title, slug\n}': POSTS_QUERY_RESULT;
    '*[_type == "post" && slug.current == $slug][0]{\n  title, body, mainImage, categories[]->{title, slug}\n}': POST_QUERY_RESULT;
    '*[_type in ["entry", "creature", "discipline", "technique", "path"] && defined(slug.current)]| order(coalesce(title, name) asc)[0...96]{\n  _id,\n  _type,\n  "title": coalesce(title, name),\n  slug,\n  description\n}': ENTRIES_QUERY_RESULT;
    'count(*[_type in ["entry", "creature", "discipline", "technique", "path"] && defined(slug.current)])': ENTRIES_COUNT_QUERY_RESULT;
    '*[_type == "entry" && slug.current == $slug][0]{\n  _type,\n  title,\n  cardDetails,\n  entryBody,\n  toc,\n  mainImage,\n  publishedAt,\n  author->{name, slug},\n  category->{title, slug, parent->{title, slug, parent->{title, slug, parent->{title, slug, parent->{}}}}}\n}': ENTRY_QUERY_RESULT;
    '*[_type in ["entry", "creature", "discipline", "technique", "path"] && slug.current == $slug][0]{\n  _type,\n  "title": coalesce(title, name),\n  slug,\n  description,\n  entryBody,\n  toc,\n  mainImage,\n  category->{title, slug, parent->{title, slug, parent->{title, slug, parent->{title, slug, parent->{}}}}},\n\n  // Entry-specific fields\n  _type == "entry" => {\n    cardDetails,\n    publishedAt,\n    author->{name, slug}\n  },\n\n  // Creature-specific fields\n  _type == "creature" => {\n    "name": name,\n    physical,\n    interpersonal,\n    intellect,\n    psyche,\n    health,\n    physicalShield,\n    psychicShield,\n    armorCapacity,\n    attacks,\n    specialAbilities,\n    challengeLevel,\n    creatureType,\n    environments,\n    isSwarm,\n    isUnique\n  },\n\n  // Discipline-specific fields\n  _type == "discipline" => {\n    paths[]->{_id, title, slug},\n    techniques[]->{_id, title, latin, slug, cooldown, description}\n  },\n\n  // Technique-specific fields\n  _type == "technique" => {\n    latin,\n    cooldown\n  },\n\n  // Path-specific fields\n  _type == "path" => {\n    latin,\n    modifiers[]{ modifierSubscore->{ _id, title, score->{ _id, title } }, modifierValue }\n  }\n}': UNIFIED_ENTRY_QUERY_RESULT;
    '*[_type == "category" && defined(slug.current)][0...12]{\n  _id, title, slug, description\n}': CATEGORIES_QUERY_RESULT;
    '*[_type == "category" && slug.current == $slug][0]{\n  _id,\n  title,\n  slug,\n  description,\n  parent->{title, slug},\n  "entries": *[_type in ["entry", "creature", "discipline", "technique", "path"] && references(^._id)]| order(coalesce(title, name) asc) [0...96]{\n    _id,\n    _type,\n    "title": coalesce(title, name),\n    slug,\n    description\n  },\n  "children": *[_type == "category" && references(^._id)]{\n    _id,\n    title,\n    slug,\n    description\n  }\n}': CATEGORY_QUERY_RESULT;
    '*[_type == "timeline"]| order(year desc) {\n  _id, title, URL, year, major, icon, description\n}': TIMELINE_QUERY_RESULT;
    '*[_type == "creature"]| order(name asc) {\n  _id,\n  name,\n  slug,\n  description,\n  mainImage,\n  physical,\n  interpersonal,\n  intellect,\n  psyche,\n  health,\n  physicalShield,\n  psychicShield,\n  armorCapacity,\n  attacks,\n  specialAbilities,\n  challengeLevel,\n  creatureType,\n  environments,\n  isSwarm,\n  isUnique\n}': CREATURES_QUERY_RESULT;
    '*[_type == "creature" && slug.current == $slug][0]{\n  _id,\n  name,\n  slug,\n  description,\n  mainImage,\n  physical,\n  interpersonal,\n  intellect,\n  psyche,\n  health,\n  physicalShield,\n  psychicShield,\n  armorCapacity,\n  attacks,\n  specialAbilities,\n  challengeLevel,\n  creatureType,\n  environments,\n  isSwarm,\n  isUnique,\n  entryBody,\n  toc,\n  category->{title, slug, parent->{title, slug, parent->{title, slug, parent->{title, slug, parent->{}}}}}\n}': CREATURE_QUERY_RESULT;
    '{\n  "environments": array::unique(*[_type == "creature"].environments[]),\n  "creatureTypes": array::unique(*[_type == "creature"].creatureType),\n  "challengeLevels": ["trivial", "easy", "moderate", "hard", "deadly"]\n}': CREATURE_FILTERS_QUERY_RESULT;
  }
}
