import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex z-10 justify-left">
          <Link className="p-5" href="/">Home</Link>
          <Link className="p-5" href="/character">Character Manager</Link>
          <Link className="p-5" href="/vorago">Vorago</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
