import type { Metadata } from "next";
import { Roboto, Inconsolata, Marcellus_SC } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Header from '@/app/components/global/Header';
import Footer from '@/app/components/global/Footer';

const roboto = Roboto({
  weight: ['400', '700'],
  variable: '--font-roboto',
  subsets: ["latin"] });
const marcellus = Marcellus_SC({
  weight: ['400'],
  variable: '--font-marcellus',
  subsets: ["latin"] });
const inconsolata = Inconsolata({
  weight: ['200','400','600'],
  variable: '--font-inconsolata',
  subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${inconsolata.variable} ${marcellus.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
